### ISSUE TITLE
Biobags in biolockers can't mass pickup slime extracts

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1184] opened 2015-11-11 05:21 UTC
Is this intended? It's much faster to take slime extracts and put it in the smartfridge by hand than to use this.

**Comment by Chronitonity** [comment] 2015-11-11 05:26
If you mean unused ones, yes because they aren't biowaste.

**Comment by McHatters** [comment] 2015-11-11 12:41
ah

**Comment by McHatters** [comment] 2015-11-11 12:43
That's weird though, because you can still put unused slime extract into the biobag Does it pick up anything else aside from slime extracts?

**Comment by Chronitonity** [comment] 2015-11-12 11:20
Syringes, beakers, bottles, blood packs, medipens, and dead mice

They're for containing "waste"

Anyway closing because not a bug

**Closed as completed by Chronitonity** 2015-11-12 11:20 UTC
