### ISSUE TITLE
SPEAKEASY BAR

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1198] opened 2015-11-13 20:21 UTC
says " ACCESS DENIED" on the bar vendomat
used to require no access pre-rebase, got FIXED, and now it's back to requiring bar access! LAME!

**Comment by Crystalwarrior** [comment] 2015-11-13 20:22
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
This is utterly retarded and should be fixed asap

**Comment by Chronitonity** [comment] 2015-11-13 22:26
Mostly intended because its a free stun dispenser, just hack it

**Comment by Carbonhello** [comment] 2015-11-22 13:42
Not a bug,close?

**Closed as completed** 2015-11-22 13:42 UTC
