### ISSUE TITLE
People with dismembered limbs can't be absorbed by changelings

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#3003] opened 2016-10-10 23:18 UTC
Was on a changeling round and I tried to absorb two people who had lost limbs. Both of them said they weren't able to be absorbed, saying "(person) cannot be considered a conscious being!" Not sure what the deal there was, they both had minds at one point.

**Comment by ArcLumin** [comment] 2016-10-11 15:05
It's not about "having a mind at one point" but "having an associated Ckey" people who have lost limbs CAN be absorbed. They just logged out, and so the game purged their Ckey from the tables, making them "braindead" and thus, unable to be absorbed.

Not a bug, and dismembered people can be absorbed, so long as they have their head and brain. Close this.

**Closed as completed** 2016-10-11 15:14 UTC

**Comment by blobbernaut** [comment] 2016-12-02 15:32
isn't that a shitty thing by itself? logging out as a dead person keeps you from getting absorbed?

**Comment by JohnGinnane** [comment] 2016-12-02 15:54
I believe absorbing beings with no CKey was implemented to stop being using monkeys to easily gain DNA

**Comment by Swagile** [comment] 2016-12-02 16:02
they can still do it, the work around is to just to debrain a succ'd dude, put his brain in a monkey, then succ that dude.

rinse and repeat; this bug has not been fixed just delegated to a harder way to do it.
