### ISSUE TITLE
Tracking Beacon microphones

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1343] opened 2015-12-01 23:07 UTC
they do not work,but the speakers do

**Comment by Spacedong** [comment] 2015-12-02 22:40
lmao who the fukk wud care bout this shit u autist

**Comment by TDcoolguy300** [comment] 2016-03-17 00:46
Not a bug, intended in the code.

**Comment by carlarc** [comment] 2016-03-17 02:03
remove the microphone then, it looks bad.
also how did this get ignored for so fucking long?

**Comment by Carbonhell** [comment] 2016-03-28 20:55
Fixed in #2013

**Closed as completed by Carbonhell** 2016-03-28 20:55 UTC
Labels: Balancing
