### ISSUE TITLE
Clothing with slowdown variable will slow you down even with item in-hand

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#2145] opened 2016-04-09 21:07 UTC
It's all fine and dandy for bulky as hell hardsuits but when you have clown shoes or galoshes in your hands you're still slowed down.
Needs to have a special flag added for this or something so we can have both the "as clothes AND in-hand" slowdown and "just when worn" slowdown.

**Comment by Spacedong** [comment] 2016-04-09 21:25
its not a bug its a feature from /tg/ rebase but REMOVE it anyway

**Comment by Kierany9** [comment] 2016-04-09 21:28
What Spacedong said

Fuck this feature, if it's for "muh immersions", you can drag it behind you anyway

**Comment by Crystalwarrior** [comment] 2016-04-09 21:28
I think straight up removing it is a bad idea too since we might have weapons that give slowdown when in-hand.
But it needs to have a code-wise flag to induce it instead of it being global even on in-hands.
Basically saying it's a good framework for future shit

**Comment by carlarc** [comment] 2016-04-10 05:00
weapons that give slowdown? what?

**Comment by TDcoolguy300** [comment] 2016-04-10 05:11
Something something Gibtonite something something. As far as the game is concerned, any item with a slowdown value is in your hands or somewhere in which it's in your contents directly, it will add slowdown.

**Comment by TDcoolguy300** [comment] 2016-04-10 05:12
Also, i am not up for removing this shit, it's used for slowdown effects on certain items and whatnot, just add a check if it's a clothing item or whatever to not apply slowdown in your hands.

**Comment by carlarc** [comment] 2016-04-10 05:26
just fucking put the galoshes in your backpack or drag them

**Comment by Pyko1** [comment] 2016-04-12 11:19
its kinda funny how bear traps slow you when you hold them, but no issue if your bag is full of em.

**Comment by JohnGinnane** [comment] 2016-04-12 11:23
Would it be more reasonable to make you slow if the item is in your backpack also?

**Comment by Carbonhell** [comment] 2016-04-13 16:01
That'd be too realistic and unfun. The current way is the best one imo. Items such as clown shoes have the benefit of being normal item aka can be put in backpack to negate the slowdown effect.At the very least we could make "gigantic" class items slow you down,or bulky ones aswell.

**Comment by JohnGinnane** [comment] 2016-04-13 16:03
That sounds much more fair. So if you're holding a hardsuit should it continue to slow you down? I'd like to think wearing the suit (or clown shoes) makes it more difficult to move whereas holding the item wouldn't really impede your movement like it does now

**Comment by Pyko1** [comment] 2016-04-13 16:05
personally I think we should have few flags for slowdown, slowdown-equipped, slowdown-heavy and slowdown-wielded.

Ie. 
slowdown-equipped slows if equipped, but not if held or in bag
slowdown-wielded slows down if equipped or held, but not in bag
slowdown-heavy slows down if equipped, wielded or in bag.

**Comment by JohnGinnane** [comment] 2016-04-13 16:43
Okay so new flag 'carry_weight' with the above flags. This could be on all items default to normal weight, and then hardsuits would be heavy equipped

**Comment by Spacedong** [comment] 2016-05-14 23:43
this isnt a bug and its a bad /tg/ feature so can someone either fix it or close it blease

**Comment by Spacedong** [comment] 2016-07-10 15:37
THIS IS A FEATURE ITS FROM MAY, CLOSE THIS

**Comment by Spacedong** [comment] 2016-07-10 16:14
THIS.IS.NOT.A.BUG. CLOSE THIS

**Comment by Spacedong** [comment] 2016-07-10 21:22
close this gandalf

**Comment by Gandalf2k15** [comment] 2016-07-10 21:24
This is a bad feature, not a bug. Its intended.

**Closed as completed by Gandalf2k15** 2016-07-10 21:24 UTC
Labels: Feature, Bug, Confirmed Bug, Bad Feature, Confirmed
