### ISSUE TITLE
Potential cause of Atmos lag:

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2433] opened 2016-05-25 19:48 UTC

**Comment by Carbonhell** [comment] 2016-05-28 13:06
caused by putting a simulated turf next to space, causing the air on said turf to leak to space
easy fix,someone do it
and no,this could only cause a slightly impact at roundstart,nothing else

**Comment by Kokojos** [comment] 2016-05-30 20:50
Mostly fixed in a recent PR, more to come.

**Closed as completed by Kokojos** 2016-05-30 20:50 UTC
