### ISSUE TITLE
Clowns remain clumsy when thralled

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2536] opened 2016-06-15 20:25 UTC
Read the title.

All other antag roles remove it.

Fix this.

**Comment by Sarcalogo** [comment] 2016-06-16 15:23
[Balance] [Controversial] [Needs Head Input] [BAD FEATURE] [Feature] [Not a Bug]

**Comment by TDcoolguy300** [comment] 2016-06-16 15:29
Technically thralling is not a round-start antag, as Thralls are created by Shadowlings. I would also like to note that clowns revved by revheads also keep their clumsy mutation. Closing.

**Closed as completed by TDcoolguy300** 2016-06-16 15:29 UTC
