### ISSUE TITLE
Emergency shuttle cannot be marked as an area by blueprints

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2137] opened 2016-04-08 23:31 UTC
This fucked me over a little when I was atmos tech during the nexendia shuttlebuild.

**Comment by Kokojos** [comment] 2016-04-08 23:53
Fairly sure this is intended as not to break the shuttle itself.

**Comment by Spacedong** [comment] 2016-04-12 21:08
why the fuck do we have a working as intended label, close it or if its an actual issue, keep it open

**Comment by Crystalwarrior** [comment] 2016-04-12 21:09
yeah I agree, working as intended is kinda silly.

**Comment by Pyko1** [comment] 2016-04-13 14:59
The label is for searching purposes mainly.

And usually when I use it, i keep issue open for couple days if someone has anything to add.

**Closed as completed by Pyko1** 2016-04-13 14:59 UTC
Labels: Working as Intended
