### ISSUE TITLE
Wraiths can spawn on-top of the AI

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#1739] opened 2016-01-25 18:03 UTC
Title.

Wraiths can spawn on top of the AI and slash it until death.
AI can literally do jackshit but screams for help and even then it's too late.

Had this happen twice to me so far.

**Comment by Spacedong** [comment] 2016-01-25 18:41
this has been in-game for years, also not a bug, close this

**Comment by Kokojos** [comment] 2016-02-02 21:40
Not a bug

**Closed as completed by Kokojos** 2016-02-02 21:40 UTC
