### ISSUE TITLE
Fire axe cabinet is invisible  

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#667] opened 2015-09-23 02:12 UTC
who the fuck fucked up DMIs? Was it @Carbonhell? or @whitefox08 maybe even @my father? 

http://puu.sh/kkTsd/f8d86cfa4a.png

**Comment by Carbonhell** [comment] 2015-09-23 15:58
Unable to reproduce?What caused that to happen?I tried to open it and remove axe and viceversa,all icons are working...

**Comment by Carbonhell** [comment] 2015-09-23 20:19
fixed in #671

**Closed as completed** 2015-09-23 20:21 UTC
