### ISSUE TITLE
chaplain spawns with riot armour

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#1850] opened 2016-02-09 06:58 UTC
this crusader armour shiet is basically reskinned riot armour
its too good
needs a nerf
tune it down to 50 or something like the barkeeps armour

![](http://puu.sh/n1gM5/6a888c42f5.png)
![](http://puu.sh/n1gMn/66cf08837e.png)

**Comment by Spacedong** [comment] 2016-02-09 22:26
w e w

**Comment by Nebyab** [comment] 2016-02-11 20:51
not a bug

**Comment by Pyko1** [comment] 2016-02-11 21:09
I assume the main issue really is https://github.com/HippieStationCode/HippieStation13/issues/1824.

**Comment by Spacedong** [comment] 2016-03-03 00:55
fixed close this

**Comment by Carbonhell** [comment] 2016-03-12 11:37
Nerf's been merged for riot armors,if the problem persists make a new issue yo

**Closed as completed by Carbonhell** 2016-03-12 11:37 UTC
Labels: Coding, Balancing, Needs Head Input
