### ISSUE TITLE
abandoned satellite doesn't need to have an APC set up to be usable

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#2085] opened 2016-03-29 20:55 UTC
http://puu.sh/nYDkg/b72ad47db0.png
valve, pls fix.
it's a simple area flag that needs to be unticked iirc.

**Comment by Spacedong** [comment] 2016-03-30 14:21
that's the abandoned satellite not the AI satellite you donk

**Comment by Crystalwarrior** [comment] 2016-03-30 14:36
ffffffffffugh

**Comment by Spacedong** [comment] 2016-03-30 16:29
btw wouldnt this make it a complete pain in the ass to repair

**Comment by JohnGinnane** [comment] 2016-03-30 16:35
Kinda yeah, but one of the cool things about the abandoned teleporter is that you have exactly what you need and no more to return home.

For example there's two shards of glass you can weld to get two sheets to make the teleporter console. This basically makes it harder to return home, but you're given materials, tools, and even air in a cannister

**Comment by Crystalwarrior** [comment] 2016-03-30 16:38
TWO air canisters in fact.
It's really kickass.

**Comment by JohnGinnane** [comment] 2016-03-30 16:52
Yeah I love that place. Adding the APC would just make it take longer, you can normally get home in under 60 seconds if you know what you're doing

**Comment by Pyko1** [comment] 2016-04-01 04:28
Technically it should have one, also only thing there using power is the teleporter so we can just slap an APC to wall and turn everything on at round start. And it will only start draining once someone actually fixes the teleporter.

**Comment by Spacedong** [comment] 2016-05-14 15:32
its not really needed imo

**Comment by Spacedong** [comment] 2016-05-30 14:26
this is not a bug, merely an opinion, close this

**Comment by Kokojos** [comment] 2016-05-30 16:40
I agree

**Closed as completed by Kokojos** 2016-05-30 16:40 UTC
Labels: Mapping, Confirmed Bug
