### ISSUE TITLE
Immovable butt doesn't work

### ISSUE THREAD

**Issue by tortellinitony** [HippieStationArchive/HippieStation13-1#3088] opened 2016-12-08 21:16 UTC
There should be a .4% chance to superfart an immovable rod. Sadly, you only get the message that your butt flies off into the galaxy and nothing to accompany it.

**Comment by blobbernaut** [comment] 2016-12-08 21:22
Yeah not even an explosion like the smaller level

**Comment by LuisReyesX** [comment] 2016-12-09 00:40
a ling was once absorbing me, i superfarted, got the rod message and nothing happened, got dissapointed.

**Comment by blobbernaut** [comment] 2016-12-09 01:54
Disappoint

**Comment by GuyonBroadway** [comment] 2016-12-10 19:18
Dupe of #2367 but I think that just goes to prove it's been unattended for so long people forgot a report was made. It's also THAT rare that nobody thinks much of it, which is a shame.

**Comment by Swagile** [comment] 2016-12-10 19:23
same i blasted off into the galaxy right infront of a group of lined up revs and nothing fucking happened

SALTY AS FUCK

**Comment by Pyko1** [comment] 2016-12-10 19:23
I was a malf ai once, and a critted player (cant be lasered) crawled in top of me (since crit people can apparently crawl in top of AI) and superfarted me to death from barely hurt.

The whole gib/ instant kill shit on meme command is shit.

**Comment by Swagile** [comment] 2016-12-10 19:25
there is such a low percentage of that happening, pyko, that its honestly just a "LMAO" moment when it actually happens. like when asskek was captain and super farted early round when he got mobbed by revs and he got lucky with an explosion fart that put a rev head and 3 revs in critical.

its just one of those moments that you love ss13

**Comment by Pyko1** [comment] 2016-12-10 19:26
well not sure about now, but old superfart used to be fuck AI up if they jsut crawled in top of it.

**Comment by Pyko1** [comment] 2016-12-10 19:28
I think AI has 100 health if i recall correctly and the turrets cant target crit crawlers.

**Comment by Pyko1** [comment] 2016-12-10 19:29
so it used to be like 2 toolbox hits and superfart at minimal effect.

**Comment by Swagile** [comment] 2016-12-10 19:29
yeah old super fart (normal, no galaxy or explosion) used to do like 80 damage

**Comment by GuyonBroadway** [comment] 2016-12-10 19:30
Twas the Bane of many a Ling, and rightly so, anything that kicks lings in the nuts a little harder is good in my book.

**Comment by Pyko1** [comment] 2016-12-10 19:34
the issue with superfart is really its about whether or not you know about it.

**Comment by Pyko1** [comment] 2016-12-10 19:34
should need you to eat special cabbage or shit and then to add ui button to do it.

**Comment by Pyko1** [comment] 2016-12-10 19:38
kinda like bomb implant, that you get randomly from certain shit you eat. And it adds the trigger button. Main issue with super fart I have is that it only has a text command to trigger that relies on knowing that shit. If everyone would just have a button to superfart at will it would be absolute shit.

Now its just an another way to have last word for regulars.

**Comment by JohnGinnane** [comment] 2016-12-10 19:48
Closing as this is a duplicate of #2367 

Will look at fixing in rebase (Might need to port superfart in the process)

**Closed as completed by JohnGinnane** 2016-12-10 19:48 UTC
Labels: Bug
