### ISSUE TITLE
you can get mulligan in crit

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2049] opened 2016-03-23 17:54 UTC
fuck

**Comment by Carbonhell** [comment] 2016-03-23 18:19
Is this really an issue,you can still be healed... Like it happened

**Comment by Crystalwarrior** [comment] 2016-03-23 18:22
uhh, if you're in crit in the first place chances are you'll be either finished off or die from "natural causes".

**Comment by Pyko1** [comment] 2016-03-23 23:23
Not a bug really, at least I see no reason to add checks for health to mulligan antags.

**Comment by carlarc** [comment] 2016-03-24 05:37
well i figure it'd be pretty annoying to have a chance to be traitor and be in crit, unable to do jack shit except whisper some dumbass your PDA code.

**Comment by Pyko1** [comment] 2016-03-25 13:28
not a bug, closing.

**Closed as completed by Pyko1** 2016-03-25 13:28 UTC
Labels: Bad Feature, Working as Intended
